language: php

php:
    - 7.2
    - 7.3
    - 7.4

jobs:
    fast_finish: true
    include:
    - php: nightly
      env: COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
    allow_failures:
        - php: nightly

env:
    global:
        - COMPOSER_ARGS="--no-interaction"
    jobs:
        - PREFER_LOWEST="--prefer-lowest --prefer-stable"
        - PREFER_LOWEST=""

before_install:
    - if [[ $TRAVIS_PHP_VERSION != "nightly" ]]; then git clone -b stable https://github.com/jedisct1/libsodium.git; fi
    - if [[ $TRAVIS_PHP_VERSION != "nightly" ]]; then cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..; fi

install:
    - if [[ $TRAVIS_PHP_VERSION != "nightly" ]]; then pecl install libsodium; fi
    - if [[ $TRAVIS_PHP_VERSION != "nightly" ]]; then echo "extension=sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi

before_script:
    - travis_retry composer self-update
    - travis_retry composer update $PREFER_LOWEST $COMPOSER_ARGS

script:
    - make travis

after_success:
    - bash <(curl -s https://codecov.io/bash)

cache:
    directories:
        - $HOME/.composer/cache
